### ISSUE TITLE
get 404 when run behind nginx

### ISSUE THREAD

**Issue by JadeVane** [rafaelespinoza/standardnotes#2]
run with

```
./bin/standardnotes api
```

configuration of nginx

```
server {
    listen 80;
    server_name mydomain.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name mydomain.com;
    ssl_certificate     /etc/letsencrypt/live/mydomain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

    # other SSL stuff...

    location / {
        proxy_pass http://localhost:8888;

        add_header Access-Control-Allow-Origin 'https://app.standardnotes.org' always;
        add_header Access-Control-Allow-Headers 'authorization,content-type' always;
        add_header Access-Control-Allow-Methods 'GET, POST, PUT, PATCH, DELETE, OPTIONS' always;
        add_header Access-Control-Expose-Headers 'Access-Token, Client, UID' always;

        if ($request_method = OPTIONS ) {
            return 200;
        }
    }

    access_log /var/log/sf-access.log;
    error_log /var/log/sf-error.log;
}
```

standardfile server show nothing error, but I get some message from `/var/log/sf-access.log`

```
... "POST /v1/users HTTP/2.0" 404 ...
```

**Comment by rafaelespinoza** [comment]
@JadeVane, have a look at the [api routes](https://github.com/rafaelespinoza/standardnotes/blob/master/internal/api/api.go#L68). There is no matching route for a `POST /v1/users` request.

I know that the canonical standardnotes has undergone some heavy development in the last 20 months or so. This server was written with the early 2020 version of standardnotes in mind. Is that route taken from another client/server API contract?

**Comment by JadeVane** [comment]
yeah, I am using the lastest version of standard notes, aka 3.8.18, which build in Jul 2021, so are there any plan to support the lastest version of standard notes?

**Comment by rafaelespinoza** [comment]
Sorry to say that I don't have any concrete plans to support the latest version(s) of StandardNotes.

I've taken a look at the infrastructural updates that have been developed this year and I don't think I'm going to have the time to properly adapt it to newer clients in the near future.

If you wanted a golang syncing server in particular, I'd suggest giving https://github.com/mdouchement/standardfile a try. It looks like there is some support for the latest API.

**Comment by JadeVane** [comment]
That's fine. anyway, Thanks for your work.
